### login user
POST http://localhost:4242/api/auth/login
Content-Type: application/json

{
  "userId": "002",
  "password": "12345678"
}

> {% client.global.set("auth_token", response.body.token) %}

### get instances
GET http://localhost:4242/api/instance

### get single instance
GET http://localhsot:4242/api/instance/2

### get questions
GET http://localhost:4242/api/instance/2/question

### get question
GET http://localhost:4242/api/instance/2/question/3

### get answer for question
GET http://localhost:4242/api/instance/2/question/3/answer

### answer question 1
POST http://localhost:4242/api/instance/2/question/1/answer
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "value": [1]
}

### answer question 3
POST http://localhost:4242/api/instance/2/question/3/answer
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "value": [
  [0],
  [0],
  [3]
]
}

### answer question 4
POST http://localhost:4242/api/instance/2/question/4/answer
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "value": "abc"
}

### getting question
GET http://localhost:4242/api/instance/2/question/3/answer
Authorization: Bearer {{auth_token}}
