### login admin
POST http://localhost:4242/api/auth/login
Content-Type: application/json

{
  "userId": "001",
  "password": "12345678"
}

> {% client.global.set("auth_token", response.body.token) %}


### login user
#POST http://localhost:4242/api/auth/login
POST http://14e04a997123.ngrok.io/api/auth/login
Content-Type: application/json

{
  "userId": "002",
  "password": "12345678"
}

> {% client.global.set("auth_token", response.body.token) %}

###
GET http://14e04a997123.ngrok.io/api/auth/get

###
GET http://localhost:4242/api/auth/protected
Authorization: Bearer {{auth_token}}

###
GET http://localhost:4242/api/survey/123
Accept: application/json

###
GET http://localhost:4242/api/survey/123/question/200

###
GET http://localhost:4242/api/survey/123/question/1

###
POST http://localhost:4242/api/survey/123/question/1/answer
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "data": [1]
}

### get aswers csv
GET http://localhost:4242/api/survey/answer-csv

### get average
GET http://localhost:4242/api/survey/3/average




