POST http://localhost:4242/api/auth/user
Content-Type: application/json

{
  "userId": "001",
  "password": "12345670",
  "role": "admin"
}

### login admin
POST http://localhost:4242/api/auth/login
Content-Type: application/json

{
  "userId": "001",
  "password": "12345678"
}

> {% client.global.set("auth_token", response.body.token) %}


### create user
POST http://localhost:4242/api/auth/user
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "userId": "005",
  "password": "12345678",
  "isAdmin": false
}

### update password
POST http://localhost:4242/api/auth/user/update-password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "userId": "005",
  "password": "12345670"
}

### login first admin
POST https://s265553-thesis-server.herokuapp.com/api/auth/login
Content-Type: application/json

{
  "userId": "root",
  "password": "12345678"
}

> {% client.global.set("auth_token", response.body.token) %}

### create user
POST https://s265553-thesis-server.herokuapp.com/api/auth/user
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "userId": "user5",
  "password": "12345678",
  "isAdmin": false
}

### login user
POST https://s265553-thesis-server.herokuapp.com/api/auth/login
Content-Type: application/json

{
  "userId": "user5",
  "password": "12345678"
}
